# Generated by Django 5.2.5 on 2025-08-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_userclientrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
    ]
