# Generated by Django 5.2.5 on 2025-08-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_items', '0002_alter_workitems_assigned_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workitems',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Work Items'},
        ),
        migrations.AlterField(
            model_name='workitems',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=50),
        ),
        migrations.AlterField(
            model_name='workitems',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
