# Generated by Django 5.2.5 on 2025-08-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
