# Generated by Django 5.2.5 on 2025-08-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_meeting_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
    ]
