# Generated by Django 5.2.5 on 2025-12-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmembers',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('member', 'Members'), ('viewer', 'Viewer')], default='member', max_length=50),
        ),
    ]
