# Generated by Django 5.2.5 on 2025-12-27 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_projectactivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSlackChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=255)),
                ('channel_name', models.CharField(max_length=255)),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slack_channels', to='project.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'channel_id')},
            },
        ),
    ]
