# Generated by Django 5.2.5 on 2025-12-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_token', models.CharField(max_length=255)),
                ('team_id', models.CharField(max_length=255, unique=True)),
                ('team_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_connected', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slack Token',
                'verbose_name_plural': 'Slack Tokens',
            },
        ),
    ]
